# Generated by Django 5.2.4 on 2025-08-26 06:58

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0002_participant_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['slide_order']},
        ),
        migrations.AlterField(
            model_name='score',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='presenter.participant'),
        ),
        migrations.AlterField(
            model_name='score',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='presenter.presentation'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='slide',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='presenter.presentation'),
        ),
    ]
