# Generated by Django 5.2.4 on 2025-08-26 07:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0003_alter_slide_options_alter_score_participant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Django Presentation System', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
